#!/bin/bash
if [ ! $# -eq 2 ]
then
    echo "Usage: $(basename $0) FILE_OR_DIRECTORY   NUMERIC_ID"
    exit 1
fi

FILEPATH=$1
NID=$2

if [ -e $NID.m3u ]
then
    echo "id $NID already exists"
    exit 1
fi

find "$FILEPATH" -type f -o -type l |sort > $NID.m3u
